apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: clusterpool-shrink
spec:
#            ┌────────────── minute (0 - 59)
#            │ ┌────────────── hour (0 - 23)
#            │ │  ┌───────────── day of the month (1 - 31)
#            │ │  │ ┌───────────── month (1 - 12)
#            │ │  │ │ ┌───────────── day of the week (0 - 6) (Sunday to Saturday;
#            │ │  │ │ │                                   7 is also Sunday on some systems)
#            │ │  │ │ │
#            │ │  │ │ │
  schedule: "* 20 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: policy-grc-sa
          containers:
          - name: clusterpool-shrink
            image: bitnami/kubectl:latest
            imagePullPolicy: IfNotPresent
            command: 
            - /bin/sh
            args:
            - -c
            - date; for pool in $(kubectl get clusterpool -n acm-grc-security -o name); do kubectl patch ${pool} -n acm-grc-security --type merge --patch '{"spec":{"size":"1"}}'; done
          restartPolicy: OnFailure